reductstore/website

src/components/HomepageCTA/index.tsx, src/components/SocialShareBar/index.tsx, src/components/SocialShareBar/styles.module.css, src/css/custom.css
- Reduce button size on landing page (Reduct AI)
- Optimize share bar for mobile
=> Rs 86 reduct ai action button is too big for mobile version

docs/http-api/bucket-api.mdx
Document JSON format of the `GET /api/v1/b/:bucket_name` response.
=> Document JSON format of the GET /api/v1/b/:bucket_name response

docusaurus.config.js, src/css/custom.css, src/pages/index.module.css, src/pages/index.tsx
This PR includes:
- Github button in header with different color in dark / light mode
- Stars in hero section which are hidden on mobile
=> RS-112: Add Github button in header and stars in hero section

package.json, src/components/Faq/FaqItem.tsx, src/components/Faq/index.tsx, src/components/Faq/styles.module.css, src/components/PricingTable/PricingPlan.tsx, src/components/PricingTable/index.tsx, src/components/PricingTable/styles.module.css, src/css/custom.css, src/pages/pricing/index.tsx, yarn.lock
This PR modifies the pricing table component and introduces a new FAQ component. Both components are used by the pricing page.
=> RS-103: New pricing offer

docs/configuration.mdx, docs/http-api/server-api.mdx, src/pages/pricing/index.tsx
CHanges
* Updated Configuration section
* Updated Server HTTP API docs
Ref  reductstore/reductstore#400
=> RS-156: Add license information in settings and API

README.md, blog/2023-07-07-mqtt-data-storage/index.md, docs/http-api/bucket-api.mdx, docs/http-api/entry-api.mdx, docs/http-api/replication-api.mdx, docs/http-api/server-api.mdx, docs/http-api/token-authentication.mdx, docusaurus.config.js, src/components/HomepageFeatures/index.tsx, src/pages/index.module.css, src/pages/index.tsx, versioned_docs/version-1.7.x/http-api/bucket-api.mdx, versioned_docs/version-1.7.x/http-api/entry-api.mdx, versioned_docs/version-1.7.x/http-api/server-api.mdx, versioned_docs/version-1.7.x/http-api/token-authentication.mdx, versioned_docs/version-1.8.x/http-api/bucket-api.mdx, versioned_docs/version-1.8.x/http-api/entry-api.mdx, versioned_docs/version-1.8.x/http-api/replication-api.mdx, versioned_docs/version-1.8.x/http-api/server-api.mdx, versioned_docs/version-1.8.x/http-api/token-authentication.mdx
This PR has a few changes:
- Correct typo that was copied on several pages of the documentation
- New set of features (replication, iterative querying, token auth)
- New title on the landing page
=> RS-151: add data replication to features on the website

docusaurus.config.js, package.json, src/plugins/docusaurus-plugin-matomo-tag-manager/index.js, yarn.lock
This PR introduces a local plugin to use Matomo tag manager
=> local plugin for matomo tag manager

src/pages/terms.mdx
CHanges:
* Removed mentions about BUSL
* Updated Services
* Fees exclude taxes
* Add information about plans
=> RS-142: Update license

README.md, docusaurus.config.js, src/components/HelpForm/index.tsx, src/theme/BlogPostItem/index.js
- New navigation menu
- Show only recent blogs on sidebar
- Add "Schedule a Technical Review" to contact form
- Use "Subject=..." parameter in URL to pre-select reason in contact form
- Remove social bar under blogs. See bug when clicking on tags, e.g. https://www.reduct.store/blog/tags/computer-vision:
=> RS-251: add product navigation in main menu

blog/2022-12-17-cpp-sdk-quick-start.mdx, blog/2023-01-09-py-sdk-quick-start.mdx, blog/2023-01-15-js-sdk-quick-start.mdx, blog/2023-03-07-cats-datasets/index.md, blog/2023-07-02-reductstore-v1_5_0-released.mdx, blog/2024-01-13-implement-data-streaming-pytorch/index.md, docs/http-api/bucket-api.mdx, staticwebapp.config.json, versioned_docs/version-1.7.x/http-api/bucket-api.mdx, versioned_docs/version-1.8.x/http-api/bucket-api.mdx, versioned_docs/version-1.9.x/http-api/bucket-api.mdx
- Stop indexing:
- paginated pages (/blog/page/*)
- Tags pages (/blog/tags/*)
- Unused search pages (/search and /search/*)
- Set UTF-8 as the default character encoding
- Resolved issues related to wrong canonical links
- Updated duplicated anchor texts
How to check noindex tag:
=> RS-247: Optimize and solve technical issues for SEO

.github/workflows/azure-static-web-apps-happy-desert-02d471d03.yml, blog/2023-07-07-mqtt-data-storage/index.mdx, docusaurus.config.js, package.json, src/components/ConsultationBanner/index.tsx, src/components/ConsultationBanner/styles.module.css, src/css/custom.css, yarn.lock
- Add banner to target blog "https://happy-desert-02d471d03-41.westeurope.4.azurestaticapps.net/blog/advice/database/mqtt-data-storage"
- Add link URL to Github repository variables
=> RS 256: Add consultancy banner to target blog

docs/configuration.mdx, docs/guides/data-ingestion.mdx, docs/guides/data-quering.mdx, versioned_docs/version-1.9.x/guides/data-ingestion.mdx, versioned_docs/version-1.9.x/guides/data-quering.mdx
* Explained how to use a data folder outside snap
* Fixed guide descriptions
=> RS-259: Update snap documentation

src/components/WhitePaperForm/index.tsx, src/pages/whitepaper/index.tsx, src/pages/whitepaper/styles.module.css
- add consultation banner on white paper page
=> RS-264: Add Consultation Banner

docusaurus.config.js, src/components/CodeSnippetExample/styles.module.css, src/components/HomepageBenefits/styles.module.css, src/components/PerformanceComparison/PerformanceComparisonData.ts, src/components/PerformanceComparison/index.tsx, src/components/PerformanceComparison/styles.module.css, src/components/PerformanceComparisonTable/index.tsx, src/components/PerformanceComparisonTable/styles.module.css, src/pages/index.module.css, src/pages/index.tsx
- benchmark comparisons next to the benefits
- new landing page title and subtitle
=> RS-272: Get the benchmark comparisons on the landing page

blog/2024-02-08-performance-comparison-reductstore-vs-minio.mdx, src/components/PerformanceComparison/PerformanceComparisonData.ts
Updated the blog and landing page for the latest versions of ReductStore and Minio
=> Update minio benchmark

blog/2024-05-16-mqtt-data-storage/index.mdx, docusaurus.config.js, src/components/SlidingBanner/styles.module.css, src/plugins/docusaurus-plugin-crisp/index.js, src/plugins/docusaurus-plugin-matomo/index.js, src/theme/cookieConsent.js
- create Matomo plugin for crisp (https://crisp.chat/en/)
- adapt white paper banner to avoid overlap with chatbox
- place cookie banner on the right
=> RS-301: Integrate crisp messenger app on website

package.json, src/components/CountdownTimer/index.tsx, src/components/FreePoCBanner/index.tsx, src/components/FreePoCBanner/styles.module.css, src/components/FreePoCForm/index.tsx, src/components/FreePoCForm/styles.module.css, src/components/HelpForm/index.tsx, src/components/HelpForm/styles.module.css, src/components/WhitePaperForm/index.tsx, src/components/WhitePaperForm/styles.module.css, src/css/custom.css, src/pages/use-cases/ai-workflows/index.tsx, src/pages/use-cases/ai-workflows/styles.module.css, src/pages/whitepaper/styles.module.css, yarn.lock
- Added free PoC form and banner with countdown timer to AI-workflow use case
- improved all forms (white paper, contact, and free PoC) to look similar and added styling for thank you message
=> RS-289: lead magnet #2 free PoC  integration

src/components/FreePoCBanner/styles.module.css, src/components/PricingTable/PricingPlan.tsx, src/components/PricingTable/index.tsx, src/components/PricingTable/styles.module.css, src/components/PromotionalBanner/index.tsx, src/components/PromotionalBanner/styles.module.css, src/pages/pricing/index.tsx
Limited offer for early adopters:
- pricing page banner
- original pice tag crossed
=> RS-302: Setup promotion campaign

.github/workflows/azure-static-web-apps-happy-desert-02d471d03.yml, docusaurus.config.js, src/components/SlidingBanner/index.tsx, src/plugins/docusaurus-plugin-matomo/index.js, src/theme/cookieConsent.js
Use matomo tag manger instead of javascript tracking code
=> RS-328: Setup matomo tag manager

src/components/FreePoCBanner/index.tsx, src/components/FreePoCForm/index.tsx, src/components/HomepageBanner/index.tsx, src/components/HomepageBanner/styles.module.css, src/components/PromotionalBanner/index.tsx, src/components/PromotionalBanner/styles.module.css, src/pages/index.tsx, src/pages/pricing/index.tsx, src/pages/pricing/styles.module.css, src/pages/use-cases/ai-workflows/index.tsx, src/pages/use-cases/vibration-sensors/index.tsx
- Remove time counters
- Add text to say that it’s when they are ready to migrate
- Add contact form on pricing page
- Mention Promotion on landing page
- Trigger chat automatically (after 5 seconds on pricing page)
=> RS-323: Update pricing page

docusaurus.config.js
* Register ReductSoftware UG  and its products on Stripe
* Update the payment links
=> CA-8: update payment links for German company

docusaurus.config.js, src/components/HomepageCTA/index.tsx, src/components/HomepageUseCase/index.tsx, src/components/PerformanceComparison/index.tsx, src/components/PerformanceComparison/styles.module.css, src/data/useCasesData.ts, src/pages/index.module.css, src/pages/index.tsx, src/pages/use-cases/ai-workflows/index.tsx, src/pages/use-cases/index.tsx
- order use cases (refactoring)
- update title and subtitle of AI use case 
- change order: start with Edge AI, then Vib. data, and CV (general, to specific)
- update hero title and subtitle
- remove empty space in benefit section
- remove link to github stars in hero banner
=> RS-352: Update ai workflow use case to edge ai

docs/configuration.mdx
Add `RS_CORS_ALLOW_ORIGIN` environment variable in documentation.
=> RS-385: Add settings for CORS

src/components/FreePoCForm/index.tsx, src/components/PricingTable/PricingPlan.tsx, src/components/PricingTable/index.tsx, src/components/PricingTable/styles.module.css, src/components/PromotionalBanner/index.tsx, src/components/PromotionalBanner/styles.module.css, src/components/RenderButtonLink/index.tsx, src/pages/pricing/index.tsx
- Replace price tags with buttons
- Open request form or direct to website on button clicks
- Add company name in PoC request form
- "Start for Free" direct to /getting-started instead of Download (@atimin to confirm; I found docs more welcoming than download page)
=> RS-398: Hide price on pricing page

docusaurus.config.js, src/css/custom.css
- new links in footer: Product & Solutions, Developers, Company, Follow Us
- update links to IoT, ROS, computer vision use cases to blog tags `/blog/tags/..`
- update hover color for footer links
=> RS-363: Organize footer with main links on the website

src/components/ImageCarousel/index.tsx
Display warning message on small screen on `/datasets` page
=> RS-379: Fix mobile version

docs/configuration.mdx
* Each resource has its own table with links to the corresponding guides.
=> RS-89: Split the settings into few tables and update text

.github/workflows/test_documentation.yml, docs/configuration.mdx, docs/guides/buckets.mdx, docs/how-does-it-work.mdx
=> RS-289: add information about hard bucket quota

docs/examples/cli/data_management_delete_query.sh, docs/examples/cli/data_management_delete_records.sh, docs/guides/data-management.mdx, versioned_docs/version-1.12.x/examples/cli/data_management_delete_query.sh, versioned_docs/version-1.12.x/examples/cli/data_management_delete_records.sh, versioned_docs/version-1.12.x/guides/data-management.mdx
* Added 2 examples for specific timestamps and time range
=> RS-522: Add CLI examples for record deletion

docs/conditional-query/comparison-operators.mdx, docs/conditional-query/index.mdx, docs/conditional-query/logical-operators.mdx, docs/http-api/entry-api/run_query.mdx, sidebars.json
* Start Conditional Query Reference with common information about syntax and types
=> RS-528: Document  conditional query engine

.pre-commit-config.yaml, docs/getting-started/index.mdx, src/components/docs/InstallClientCLI/CargoInstall.tsx, src/components/docs/InstallClientCLI/WindowsInstall.tsx, src/components/docs/InstallReductStore/AzureInstall.tsx, src/components/docs/InstallReductStore/WindowsInstall.tsx, src/components/homepage/ClientSDKs/index.tsx
* Fix documentation for windows and rust users
=> RS-536: Fix download and getting started pages

package.json, src/components/homepage/HomepageBanner/styles.module.css, src/components/promotional/PromotionalBanner/index.tsx, src/pages/index.tsx, src/pages/pricing/index.tsx, yarn.lock
- update the landing page call to action
- move the banner on top of the pricing page
- make the proposition actionnable with React Calendly
- review landing page description
=> KAN-29: Update PoC on website for something more actionnable

docs/conditional-query/logical-operators.mdx
* Document logical operators in conditional query reference.
=> RS-545: Document logical operators

docs/http-api/entry-api/run_query.mdx
* Document strict flag in the query endpoint
=> RS-538: Document strict flag

docs/conditional-query/arithmetic-operators.mdx, docs/conditional-query/index.mdx, sidebars.json
* Document the new arithmetic operators.
=> RS-531: add docs for arithmetic operators

docs/conditional-query/index.mdx, docs/configuration.mdx, docs/getting-started/common/next_steps.mdx, docs/getting-started/with-cpp.mdx, docs/getting-started/with-javascript.mdx, docs/getting-started/with-python.mdx, docs/getting-started/with-rust.mdx, docs/guides/access-control.mdx, docs/guides/buckets.mdx, docs/guides/data-ingestion.mdx, docs/guides/data-management.mdx, docs/guides/data-querying.mdx, docs/guides/data-replication.mdx, docs/how-does-it-work.mdx, versioned_docs/version-1.13.x/conditional-query/index.mdx, versioned_docs/version-1.13.x/configuration.mdx, versioned_docs/version-1.13.x/getting-started/with-cpp.mdx, versioned_docs/version-1.13.x/getting-started/with-javascript.mdx, versioned_docs/version-1.13.x/getting-started/with-python.mdx, versioned_docs/version-1.13.x/getting-started/with-rust.mdx, versioned_docs/version-1.13.x/guides/access-control.mdx, versioned_docs/version-1.13.x/guides/buckets.mdx, versioned_docs/version-1.13.x/guides/data-ingestion.mdx, versioned_docs/version-1.13.x/guides/data-management.mdx, versioned_docs/version-1.13.x/guides/data-querying.mdx, versioned_docs/version-1.13.x/guides/data-replication.mdx, versioned_docs/version-1.13.x/how-does-it-work.mdx
* Update the "How Does It Work?" document
=> RS-576: Expose that we have conditional query on How Does It Work page

docs/conditional-query/string-operators.mdx, sidebars.json
* Added String Operators to Conditional Query Reference
=> RS-530: Document string operators

docs/conditional-query/misc-operators.mdx, docs/glossary.mdx, sidebars.json
* Add reference for new misc operators
* Add label to glossary
=> RS-532:  Misc operators

docs/conditional-query/logical-operators.mdx
=> RS-549: Add reference to $in/$nin operators

docs/getting-started/with-cpp.mdx
Update C++ getting started guide.
=> Update reduct-cpp installation instruction

docs/configuration.mdx, docs/examples/js/src/data_querying_filter.mjs, docs/http-api/entry-api/index.mdx, docs/http-api/index.mdx
* Add IO settings to the configuration document 
* Link to the HTTP reference and add explanation about the HTTP 1/1 limits
=> RS-597: Describe I/O settings

docs/configuration.mdx
* Document new replication settings
=> RS-243: Document replication new settings

docs/conditional-query/index.mdx, docs/configuration.mdx, docs/glossary.mdx, docs/http-api/entry-api/run_query.mdx
* Update Configuration
*  Explain Calculated Labels
* Add Calculated Labels and Extensions to Glossary 
* Update Entry API
=> RS-628: document changes for extension system

docs/examples/py/src/ext_select_query.py, docs/extensions/index.mdx, docs/extensions/official/select-ext.mdx, docs/sdk/py/index.mdx
Document https://github.com/reductstore/reductstore/pull/838
=> Update extension documentation for new staging

src/pages/terms.mdx
* Add `16. Updates to Terms' to make it clear when new changes to the terms are applied.
=> Updates terms part

.gitignore, docs/examples/go/src/access_control_browse_tokens.go, docs/examples/go/src/access_control_create_token.go, docs/examples/go/src/access_control_remove_token.go, docs/examples/go/src/data_replication_browse.go, docs/examples/go/src/data_replication_create.go, docs/examples/go/src/data_replication_remove.go, docs/guides/access-control.mdx, docs/guides/data-management.mdx, docs/guides/data-replication.mdx, src/pages/terms.mdx, versioned_docs/version-1.15.x/examples/go/src/access_control_browse_tokens.go, versioned_docs/version-1.15.x/examples/go/src/access_control_create_token.go, versioned_docs/version-1.15.x/examples/go/src/access_control_remove_token.go, versioned_docs/version-1.15.x/examples/go/src/buckets_create.go, versioned_docs/version-1.15.x/examples/go/src/data_replication_browse.go, versioned_docs/version-1.15.x/examples/go/src/data_replication_create.go, versioned_docs/version-1.15.x/examples/go/src/data_replication_remove.go, versioned_docs/version-1.15.x/guides/access-control.mdx, versioned_docs/version-1.15.x/guides/data-replication.mdx
=> Add Go  snippets to replication and access control guides

docs/guides/access-control.mdx
Document changes from  https://github.com/reductstore/reductstore/pull/849
=> Update access table

docs/conditional-query/aggregation-operators.mdx, docs/conditional-query/index.mdx
See https://github.com/reductstore/reductstore/pull/864
=> Document durataion type

docs/conditional-query/directives.mdx, docs/conditional-query/index.mdx, docs/glossary.mdx, sidebars.json
https://github.com/reductstore/reductstore/pull/866
=> Document context directives

docs/http-api/entry-api/read_data.mdx
Document https://github.com/reductstore/reductstore/pull/876
=> x-reduct-last header is removed

blog/2025-05-13-how-to-calibrate-camera-and-lidar/index.mdx, docs/conditional-query/directives.mdx, docs/examples/py/src/ext_ros_mcap_extract.py, docs/examples/py/src/ext_ros_mcap_extract_jpeg.py, docs/examples/py/src/ext_ros_mcap_transform.py, docs/examples/py/src/ext_select_csv_query.py, docs/examples/py/src/ext_select_csv_query_with_headers.py, docs/examples/py/src/ext_select_json_query.py, docs/extensions/index.mdx, docs/extensions/official/ros-ext.mdx, docs/extensions/official/select-ext.mdx, docs/guides/cloud/saas.mdx, versioned_docs/version-1.15.x/guides/cloud/saas.mdx, versioned_docs/version-1.16.x/conditional-query/directives.mdx, versioned_docs/version-1.16.x/guides/cloud/saas.mdx
https://github.com/reductstore/reductstore/pull/932
=> Document #ext directive
